--------------------------------------------------------
--  文件已创建 - 星期三-四月-12-2017
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MWM_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "LOYAL"."MWM_ACCOUNT"
   (	"M_ID" VARCHAR2(18 BYTE),
	"M_PASSWORD" VARCHAR2(18 BYTE),
	"M_NICKNAME" VARCHAR2(18 BYTE),
	"M_ICON" BLOB,
	"M_SIGNATURE" VARCHAR2(100 BYTE),
	"M_LOCK" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("M_ICON") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into LOYAL.MWM_ACCOUNT
SET DEFINE OFF;
Insert into LOYAL.MWM_ACCOUNT (M_ID,M_PASSWORD,M_NICKNAME,M_SIGNATURE,M_LOCK) values ('admin','111111','admin',null,'0');
Insert into LOYAL.MWM_ACCOUNT (M_ID,M_PASSWORD,M_NICKNAME,M_SIGNATURE,M_LOCK) values ('l6yang','147258369','l6yang','其实我真的不懂','0');
Insert into LOYAL.MWM_ACCOUNT (M_ID,M_PASSWORD,M_NICKNAME,M_SIGNATURE,M_LOCK) values ('mr','111111','mr',null,'0');
--------------------------------------------------------
--  DDL for Index M_FID
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOYAL"."M_FID" ON "LOYAL"."MWM_ACCOUNT" ("M_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MWM_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "LOYAL"."MWM_ACCOUNT" ADD CONSTRAINT "M_FID" PRIMARY KEY ("M_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

  ALTER TABLE "LOYAL"."MWM_ACCOUNT" MODIFY ("M_ID" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_ACCOUNT" MODIFY ("M_PASSWORD" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_ACCOUNT" MODIFY ("M_NICKNAME" NOT NULL ENABLE);
