--------------------------------------------------------
--  文件已创建 - 星期三-四月-12-2017
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MWM_CONTACT
--------------------------------------------------------

  CREATE TABLE "LOYAL"."MWM_CONTACT"
   (	"CON_TIME" DATE,
	"CON_ACCOUNT" VARCHAR2(18 BYTE),
	"CON_CONTACT" VARCHAR2(18 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into LOYAL.MWM_CONTACT
SET DEFINE OFF;
Insert into LOYAL.MWM_CONTACT (CON_TIME,CON_ACCOUNT,CON_CONTACT) values (to_date('28-2月 -17','DD-MON-RR'),'l6yang','admin');
--------------------------------------------------------
--  DDL for Index CON_PGROUP
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOYAL"."CON_PGROUP" ON "LOYAL"."MWM_CONTACT" ("CON_ACCOUNT", "CON_CONTACT")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MWM_CONTACT
--------------------------------------------------------

  ALTER TABLE "LOYAL"."MWM_CONTACT" ADD CONSTRAINT "CON_PGROUP" PRIMARY KEY ("CON_ACCOUNT", "CON_CONTACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

  ALTER TABLE "LOYAL"."MWM_CONTACT" MODIFY ("CON_ACCOUNT" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_CONTACT" MODIFY ("CON_CONTACT" NOT NULL ENABLE);
