--------------------------------------------------------
--  文件已创建 - 星期三-四月-12-2017
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MWM_FEED_BACK
--------------------------------------------------------

  CREATE TABLE "LOYAL"."MWM_FEED_BACK"
   (	"F_TIME" DATE,
	"F_ID" VARCHAR2(18 BYTE),
	"C_CONTENT" VARCHAR2(600 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into LOYAL.MWM_FEED_BACK
SET DEFINE OFF;
Insert into LOYAL.MWM_FEED_BACK (F_TIME,F_ID,C_CONTENT) values (to_date('01-3月 -17','DD-MON-RR'),'admin','兔兔');
Insert into LOYAL.MWM_FEED_BACK (F_TIME,F_ID,C_CONTENT) values (to_date('28-2月 -17','DD-MON-RR'),'l6yang','默默哦？？');
--------------------------------------------------------
--  DDL for Index F_FTIME
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOYAL"."F_FTIME" ON "LOYAL"."MWM_FEED_BACK" ("F_TIME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MWM_FEED_BACK
--------------------------------------------------------

  ALTER TABLE "LOYAL"."MWM_FEED_BACK" ADD CONSTRAINT "F_FTIME" PRIMARY KEY ("F_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

  ALTER TABLE "LOYAL"."MWM_FEED_BACK" MODIFY ("F_TIME" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_FEED_BACK" MODIFY ("F_ID" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_FEED_BACK" MODIFY ("C_CONTENT" NOT NULL ENABLE);
