--------------------------------------------------------
--  文件已创建 - 星期五-四月-14-2017
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MWM_CONTACT
--------------------------------------------------------

  CREATE TABLE "LOYAL"."MWM_CONTACT"
   (	"ACCOUNT" VARCHAR2(18 BYTE),
	"CONTACT" VARCHAR2(18 BYTE),
	"TIME" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "LOYAL"."TEST"
   (	"YHDH" VARCHAR2(20 BYTE),
	"HPHM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MWM_USER
--------------------------------------------------------

  CREATE TABLE "LOYAL"."MWM_USER"
   (	"ACCOUNT" VARCHAR2(18 BYTE),
	"PASSWORD" VARCHAR2(18 BYTE),
	"NICKNAME" VARCHAR2(18 BYTE),
	"ICON" BLOB,
	"SIGN" VARCHAR2(100 BYTE),
	"LOCKED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("ICON") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;


   COMMENT ON COLUMN "LOYAL"."MWM_USER"."ACCOUNT" IS '用户账号';

   COMMENT ON COLUMN "LOYAL"."MWM_USER"."PASSWORD" IS '密码';

   COMMENT ON COLUMN "LOYAL"."MWM_USER"."NICKNAME" IS '昵称';

   COMMENT ON COLUMN "LOYAL"."MWM_USER"."ICON" IS '头像';

   COMMENT ON COLUMN "LOYAL"."MWM_USER"."SIGN" IS '签名';

   COMMENT ON COLUMN "LOYAL"."MWM_USER"."LOCKED" IS '是否被设备锁定(1表示被锁，0表示未锁 )';
--------------------------------------------------------
--  DDL for Table MWM_UPDATE
--------------------------------------------------------

  CREATE TABLE "LOYAL"."MWM_UPDATE"
   (	"NAME" VARCHAR2(20 BYTE),
	"VERSION" VARCHAR2(20 BYTE) DEFAULT 0,
	"APK" BLOB,
	"TIME" DATE,
	"ZT" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
 LOB ("APK") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table MWM_SAFETY
--------------------------------------------------------

  CREATE TABLE "LOYAL"."MWM_SAFETY"
   (	"ACCOUNT" VARCHAR2(18 BYTE),
	"TIME" DATE,
	"DEVICE" VARCHAR2(30 BYTE),
	"SERIAL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


   COMMENT ON COLUMN "LOYAL"."MWM_SAFETY"."ACCOUNT" IS '账号';

   COMMENT ON COLUMN "LOYAL"."MWM_SAFETY"."TIME" IS '绑定日期';

   COMMENT ON COLUMN "LOYAL"."MWM_SAFETY"."DEVICE" IS '设备';

   COMMENT ON COLUMN "LOYAL"."MWM_SAFETY"."SERIAL" IS '设备序列号';
--------------------------------------------------------
--  DDL for Table MWM_FEEDBACK
--------------------------------------------------------

  CREATE TABLE "LOYAL"."MWM_FEEDBACK"
   (	"ACCOUNT" VARCHAR2(18 BYTE),
	"CONTENT" VARCHAR2(600 BYTE),
	"TIME" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


   COMMENT ON COLUMN "LOYAL"."MWM_FEEDBACK"."CONTENT" IS '内容';

   COMMENT ON COLUMN "LOYAL"."MWM_FEEDBACK"."TIME" IS '时间';
REM INSERTING into LOYAL.MWM_CONTACT
SET DEFINE OFF;
Insert into LOYAL.MWM_CONTACT (ACCOUNT,CONTACT,TIME) values ('1','1',null);
Insert into LOYAL.MWM_CONTACT (ACCOUNT,CONTACT,TIME) values ('1','2',null);
Insert into LOYAL.MWM_CONTACT (ACCOUNT,CONTACT,TIME) values ('2','2',null);
Insert into LOYAL.MWM_CONTACT (ACCOUNT,CONTACT,TIME) values ('2','1',null);
REM INSERTING into LOYAL.TEST
SET DEFINE OFF;
Insert into LOYAL.TEST (YHDH,HPHM) values ('admin','AA2008');
Insert into LOYAL.TEST (YHDH,HPHM) values ('l6yang','ATN310');
REM INSERTING into LOYAL.MWM_USER
SET DEFINE OFF;
Insert into LOYAL.MWM_USER (ACCOUNT,PASSWORD,NICKNAME,SIGN,LOCKED) values ('loyal','111111','FGERTWERT','y',0);
Insert into LOYAL.MWM_USER (ACCOUNT,PASSWORD,NICKNAME,SIGN,LOCKED) values ('qweqeq','qwerasdf','sdfgdfg',null,0);
REM INSERTING into LOYAL.MWM_UPDATE
SET DEFINE OFF;
REM INSERTING into LOYAL.MWM_SAFETY
SET DEFINE OFF;
REM INSERTING into LOYAL.MWM_FEEDBACK
SET DEFINE OFF;
Insert into LOYAL.MWM_FEEDBACK (ACCOUNT,CONTENT,TIME) values ('loyal','23423sfdfgdf',to_date('14-4月 -17','DD-MON-RR'));
Insert into LOYAL.MWM_FEEDBACK (ACCOUNT,CONTENT,TIME) values ('loyal','3534534',to_date('14-4月 -17','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index UK_CONTACT
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOYAL"."UK_CONTACT" ON "LOYAL"."MWM_CONTACT" ("ACCOUNT", "CONTACT")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MWM_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOYAL"."MWM_USER_PK" ON "LOYAL"."MWM_USER" ("ACCOUNT")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_VER_VERSION
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOYAL"."UK_VER_VERSION" ON "LOYAL"."MWM_UPDATE" ("VERSION")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SAFETY_ACCOUNT
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOYAL"."PK_SAFETY_ACCOUNT" ON "LOYAL"."MWM_SAFETY" ("ACCOUNT")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_SAFETY_SERIAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOYAL"."UK_SAFETY_SERIAL" ON "LOYAL"."MWM_SAFETY" ("SERIAL")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MWM_CONTACT
--------------------------------------------------------

  ALTER TABLE "LOYAL"."MWM_CONTACT" MODIFY ("ACCOUNT" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_CONTACT" ADD CONSTRAINT "UK_CONTACT" UNIQUE ("ACCOUNT", "CONTACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "LOYAL"."TEST" MODIFY ("YHDH" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."TEST" MODIFY ("HPHM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MWM_USER
--------------------------------------------------------

  ALTER TABLE "LOYAL"."MWM_USER" ADD CONSTRAINT "PK_USER_ACCOUNT" PRIMARY KEY ("ACCOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

  ALTER TABLE "LOYAL"."MWM_USER" MODIFY ("ACCOUNT" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MWM_UPDATE
--------------------------------------------------------

  ALTER TABLE "LOYAL"."MWM_UPDATE" ADD CONSTRAINT "UK_VER_VERSION" UNIQUE ("VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MWM_SAFETY
--------------------------------------------------------

  ALTER TABLE "LOYAL"."MWM_SAFETY" ADD CONSTRAINT "PK_SAFETY_ACCOUNT" PRIMARY KEY ("ACCOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;

  ALTER TABLE "LOYAL"."MWM_SAFETY" MODIFY ("ACCOUNT" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_SAFETY" MODIFY ("TIME" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_SAFETY" MODIFY ("DEVICE" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_SAFETY" MODIFY ("SERIAL" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_SAFETY" ADD CONSTRAINT "UK_SAFETY_SERIAL" UNIQUE ("SERIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MWM_FEEDBACK
--------------------------------------------------------

  ALTER TABLE "LOYAL"."MWM_FEEDBACK" MODIFY ("ACCOUNT" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_FEEDBACK" MODIFY ("CONTENT" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_FEEDBACK" MODIFY ("TIME" NOT NULL ENABLE);
