--------------------------------------------------------
--  文件已创建 - 星期三-四月-12-2017
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MWM_VER
--------------------------------------------------------

  CREATE TABLE "LOYAL"."MWM_VER"
   (	"APK_NAME" VARCHAR2(20 BYTE),
	"APK_VERSION" VARCHAR2(20 BYTE),
	"APK_URL" BLOB,
	"APK_TIME" DATE,
	"APK_ZT" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("APK_URL") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into LOYAL.MWM_VER
SET DEFINE OFF;
Insert into LOYAL.MWM_VER (APK_NAME,APK_VERSION,APK_TIME,APK_ZT) values ('mwm_1.0.0.apk','1.0.0',to_date('03-3月 -17','DD-MON-RR'),'1');
--------------------------------------------------------
--  Constraints for Table MWM_VER
--------------------------------------------------------

  ALTER TABLE "LOYAL"."MWM_VER" MODIFY ("APK_NAME" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_VER" MODIFY ("APK_TIME" NOT NULL ENABLE);

  ALTER TABLE "LOYAL"."MWM_VER" MODIFY ("APK_ZT" NOT NULL ENABLE);
